### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by Shadow271006** [Shadow271006/Datalux-Osintgram#1]
Traceback (most recent call last):
  File "/home/kali/Osintgram/main.py", line 121, in <module>
    api = Osintgram(args.id, args.file, args.json, args.command, args.output, args.cookies)
  File "/home/kali/Osintgram/src/Osintgram.py", line 47, in __init__
    self.login(u, p)
  File "/home/kali/Osintgram/src/Osintgram.py", line 1114, in login
    self.api = AppClient(
  File "/home/kali/.local/lib/python3.10/site-packages/instagram_private_api/client.py", line 105, in __init__
    user_settings.get('uuid') or self.generate_uuid(False))
AttributeError: 'str' object has no attribute 'get'

**Comment by Luna722** [comment]
Same issue 🤦🏻‍♀️ any solution
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/Osintgram/main.py", line 3, in <module>
    from src.Osintgram import Osintgram
  File "/data/data/com.termux/files/home/downloads/Osintgram/src/Osintgram.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
(venv) ~/downloads/Osintgram $ python3 main.py <john_fox77>
bash: syntax error near unexpected token `newline'
(venv) ~/downloads/Osintgram $ python3 main.py john_fox77 --cookies
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/Osintgram/main.py", line 3, in <module>
    from src.Osintgram import Osintgram
  File "/data/data/com.termux/files/home/downloads/Osintgram/src/Osintgram.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Luna722** [comment]
Same issue solution plz 🤦🏻‍♀️
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/Osintgram/main.py", line 3, in <module>
    from src.Osintgram import Osintgram
  File "/data/data/com.termux/files/home/downloads/Osintgram/src/Osintgram.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
